package org.cbitcoin.wallets.fullnode;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.cbitcoin.wallets.fullnode.daemon.CBTCClientCaller;
import org.cbitcoin.wallets.fullnode.ui.CBTCWalletUI;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertNotNull;

public class CBTCWalletUITest {
    @Test
    public void testAppHasAGreeting() throws InterruptedException, CBTCClientCaller.WalletCallException, IOException {
        CBTCWalletUI classUnderTest = null;
        classUnderTest = new CBTCWalletUI(null,"CBTC Wallet TEST");
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
